/**
 * Card decks for the /play games — truth-or-dare and would-you-rather. Sweet,
 * couple-y, and doable whether you're on the same couch or far apart. Some
 * cards are a little spicier (it's a couple's app) but kept tasteful. Purely
 * client content; no backend.
 */

/**
 * Pick a random item from `pool` that hasn't shown up in the last few draws, so
 * the same card never repeats "right after a couple more". `recent` is a
 * most-recent-first history; returns the pick plus the updated history. The
 * remembered window is capped below the pool size so there's always something
 * fresh to draw.
 */
export function pickFresh<T>(pool: T[], recent: T[]): { pick: T; recent: T[] } {
  if (pool.length === 0) return { pick: undefined as unknown as T, recent };
  const memory = Math.min(pool.length - 1, 25);
  const avoid = new Set(recent);
  const fresh = pool.filter((x) => !avoid.has(x));
  const choices = fresh.length ? fresh : pool;
  const pick = choices[Math.floor(Math.random() * choices.length)];
  return { pick, recent: [pick, ...recent].slice(0, memory) };
}

export const TRUTHS: string[] = [
  // — first feelings & the early days —
  "what was your very first impression of me?",
  "when did you realise you were falling for me?",
  "what's the exact moment you knew this was real?",
  "what's something about our beginning you'd never change?",
  "were you nervous on our first date? be honest 😅",
  "what did you tell your friends about me at the start?",
  "what's the first thing you noticed about me?",
  "did you stalk my photos before we met properly? 👀",
  "what's a text I sent early on that you still remember?",
  "when did you first call me 'mine' in your head?",
  // — tiny things & everyday love —
  "what's a tiny thing I do that you secretly love?",
  "what's a habit of mine you'd happily put up with forever?",
  "what's the most ordinary moment with me you treasure?",
  "what sound or word of mine instantly calms you?",
  "what's a little ritual of ours you never want to lose?",
  "what's the first thing you'd want to do if I walked in right now?",
  "what part of your day do I make better without trying?",
  "what's something small I do that you'd miss the most?",
  "what's a face I make that you find adorable?",
  "when do you feel the most 'us'?",
  // — favourites & memories —
  "what's a moment with me you'd relive on repeat?",
  "what's your favourite photo of us, and why?",
  "what song instantly reminds you of me?",
  "what's the best gift I've ever given you?",
  "what's a memory of us you replay when you're sad?",
  "what's the funniest thing that's happened to us?",
  "what's our most underrated date so far?",
  "what's a smell or place that brings me to mind?",
  "what's the happiest you've ever seen me?",
  "what's a moment you wish we'd caught on camera?",
  // — distance, missing, longing —
  "what do you miss most when we're apart?",
  "what's the first thing you want to do when we're together again?",
  "what's something you wish I was here for right now?",
  "what do you do when you can't sleep and you're missing me?",
  "what's a normal thing that suddenly makes you think of me?",
  // — the soft, deeper ones —
  "what's something you've never told me but want to?",
  "what's the most thoughtful thing I've ever done for you?",
  "what made you smile about me today?",
  "what's one thing you want more of from us?",
  "when do you feel most loved by me?",
  "what's a fear about us you've never said out loud?",
  "what part of yourself do you only show me?",
  "what's something you forgive me for over and over?",
  "what do you think I love most about you?",
  "what's a way I've changed you for the better?",
  "what do you hope I never find out? (kidding… or not 😏)",
  "what's the hardest thing you've gone through that I helped with?",
  "what's a compliment of mine you still think about?",
  "what's something you admire about me but rarely say?",
  "when were you most proud to be with me?",
  // — dreams & the future —
  "what's a dream you want us to chase together?",
  "where do you most want to travel with me?",
  "what does a perfect lazy day with me look like?",
  "what does our home look like in your head?",
  "what's a tradition you want us to start?",
  "what do you imagine us laughing about when we're old?",
  "what's one promise you'd make to me right now?",
  "where do you see us in five years?",
  "what's a tiny goal you secretly want us to hit this year?",
  "what would your ideal anniversary look like?",
  // — playful & a little spicy —
  "what's the most embarrassing thing you've done because of me?",
  "what's a nickname for me you've thought of but never used?",
  "what's the cheesiest thought you've had about me?",
  "what's something about me you find ridiculously attractive?",
  "rate my flirting out of 10 — and explain 😏",
  "what's a moment you wanted to kiss me but didn't?",
  "what outfit of mine is your absolute favourite?",
  "what's the most you've ever blushed because of me?",
  "what's a daydream about me you'd be shy to admit?",
  "if you could read my mind for one minute, when would it be?",
  // — spicier 🌶️ (still tasteful — skip any that aren't your vibe) —
  "what's the first thing that crosses your mind when you see me after a while? 😏",
  "what's something I wear that you can't stop staring at? 👀",
  "where's your favourite place for me to kiss you? 💋",
  "what's a fantasy about us you've been a little shy to share? 🌶️",
  "what's the most turned-on you've ever been because of me? 🔥",
  "what's something you want me to do more often… in private? 🤫",
  "what's your favourite memory of us being a little reckless? 😈",
  "what part of me do you find the most irresistible? 💞",
  "what's a moment you really wanted me but kept it cool? 🥵",
  "what's the boldest thing you'd whisper to me right now? 🫦",
  "what's something that always gets you in the mood for me? 🌹",
  "describe our best kiss in as much detail as you dare 💋",
  "what's a 'we should try that' idea you've kept to yourself? 😏",
  "what outfit do you secretly wish I'd wear just for you? 👗",
  "what's the most you've missed me… in that way? 🌙",
];

export const DARES: string[] = [
  // — send / show me something —
  "send me the last photo in your camera roll, no explaining 📸",
  "show me your phone wallpaper and the story behind it 📱",
  "send me a selfie with the silliest face you can make 🤪",
  "screenshot your most-used emoji and explain it 😂",
  "send me the last song you had on repeat 🎧",
  "send me a photo of where you are right now 📍",
  "show me the oldest photo of us you have saved 🖼️",
  "send me a voice note saying 'i love you' in a movie-trailer voice 🎬",
  "find a photo of us and caption it like a meme 🤳",
  "send me three random things within arm's reach 🫳",
  // — say / write something sweet —
  "text me three things you love about me — go 💌",
  "say something cheesy and mean it 🧀💗",
  "give me the most dramatic compliment you can 🎭",
  "tell me a memory of us you think I forgot 🫶",
  "describe me using only emojis ✨",
  "write me a tiny two-line poem right now ✍️",
  "list five things you're grateful for about us 🙏",
  "tell me your favourite thing about today ☀️",
  "finish this out loud: 'i can't wait until we…' 💭",
  "say one thing you've never thanked me for 🤍",
  "give me a brand-new nickname and use it the rest of the game 🏷️",
  "tell me what you'd name our future pet 🐾",
  // — do something silly —
  "do your best impression of me right now 😄",
  "do a happy dance for 10 seconds 💃",
  "serenade me with 10 seconds of any song 🎤",
  "voice-note me 'goodnight' in the silliest voice 🎙️",
  "talk in an accent until your next turn 🗣️",
  "do your best evil-villain laugh 😈",
  "balance something on your head for 15 seconds 🤹",
  "sing your text-back to me instead of typing it 🎵",
  "do 10 jumping jacks and send proof 🏃",
  "make up a 5-second jingle about us 🎶",
  "pose like you're on a magazine cover and send it 📰",
  "speak only in questions until your next turn ❓",
  // — together / for later —
  "plan our next date in one sentence, right now 🗓️",
  "give me a 20-second shoulder rub (or promise one for later) 🤲",
  "recreate our first selfie pose 🤳",
  "draw a tiny heart somewhere and send proof ❤️",
  "promise me one specific thing for our next time together 🤞",
  "add a new song to 'our' playlist right now 🎼",
  "pick the next place we travel and tell me why ✈️",
  "set a reminder for a surprise for me this week ⏰",
  "plan our perfect lazy sunday out loud 🛋️",
  "decide what we're cooking together next 🍳",
  // — sweet & a little flirty —
  "blow me a kiss on camera 😘",
  "send me a wink and a one-word compliment 😉",
  "tell me the most attractive thing i did this week 🔥",
  "describe our last hug in detail 🤗",
  "look me in the eyes for 20 seconds, no laughing 👀",
  "whisper my favourite compliment (i'll know which one) 🤫",
  "tell me what you'd do first if i were right next to you 💞",
  "rate this game so far and dare me back 🔁",
  // — spicier 🌶️ (still tasteful — skip any that aren't your vibe) —
  "send me a flirty selfie that's just for me 📸🔥",
  "describe in detail what you'd do if i walked in right now 🫦",
  "whisper the cheekiest thing on your mind 🤫",
  "send me a one-line text that'd make me blush 😳",
  "bite your lip and look at the camera for 5 seconds 😏",
  "tell me your favourite thing about kissing me 💋",
  "send a voice note saying my name the way you do when we're close 🎙️",
  "describe your ideal 'no interruptions' night with me 🌙",
  "show me the outfit you'd wear to drive me crazy 👗",
  "give me a slow, dramatic wink and a 'come here' 😉",
  "tell me where you'd want my hands right now 🫳🔥",
  "send me the most flirtatious emoji combo you can 😈💞",
  "promise me one bold thing for the next time we're alone 🤞",
  "rate how much you're missing me physically, 1–10, then explain 🥵",
];

/**
 * 18+ 🔞 decks — explicit and grown, built to reignite the spark over distance:
 * desire, fantasies, reveals, partner's-choice outfits, day-long tasks, and
 * subtle consensual dom/sub power-play. Gated behind the /play "spicy mode"
 * toggle (off by default) so they only appear when both partners switch it on.
 * Always consensual: skip any card freely, agree on a safeword, and only do
 * what you're both comfortable with.
 */
export const TRUTHS_18: string[] = [
  // — desire & turn-ons —
  "what's your absolute favourite thing I do to you in bed? 🛏️",
  "what's a turn-on of yours I might not know about yet? 🔥",
  "where do you most love being touched? 🫦",
  "what's the hottest thing we've ever done together? 😈",
  "what do you think about when you touch yourself and think of me? 💭",
  "what's your favourite position with me, honestly? 🛏️",
  "morning, night, or middle-of-the-day — when do you want me most? 🕯️",
  "what's the quickest way I can drive you wild? ⚡",
  "do you prefer it slow and teasing or fast and hungry? 🌊",
  "what do I wear (or not wear) that drives you crazy? 👙",
  "what's a sound or word from me that turns you on instantly? 🎙️",
  "how do you like to be kissed when things heat up? 💋",
  "what's one thing you'd love me to do more often in the bedroom? 🔁",
  "what's the most intense moment we've shared together? 🥵",
  "what's the loudest I've ever made you? 🙊",
  "what's your favourite thing to do to me? 😏",
  // — fantasies & curiosity —
  "is there something new you want to try with me? 🌶️",
  "what's a fantasy you'd actually want to act out with me? 🎭",
  "what's the naughtiest place you'd want to be with me? 🤫",
  "what's something you've imagined us doing but never said out loud? 🙊",
  "what's a toy or prop you'd be curious to try together? 🧸",
  "what's a roleplay scenario you secretly want to do? 🎬",
  "is there a kink you've been too shy to tell me about? 🔓",
  "what's the most public place you'd dare to fool around? 😳",
  "what would your perfect 'lose all control' night look like? 🌙",
  "what's something you'd let me do that you'd never tell anyone? 🤐",
  // — power-play (consensual) —
  "do you like being in charge, or being told what to do? 👑",
  "what's a command you'd love to give me in bed? 🗣️",
  "what's an order from me you'd happily obey? 🫡",
  "would you rather tie me up or be tied up? 🪢",
  "how does it feel when I take control? 🔥",
  "what's a 'rule' you'd want me to follow for a whole night? 📜",
  "what's the most submissive thing you'd do for me? 🙇",
  "what's the most dominant thing you'd want to try on me? 😈",
  "blindfold or no blindfold — which turns you on more? 🙈",
  "what's a punishment-or-reward game you'd want to play? 🎲",
  // — subtle dom/sub & control (consensual) —
  "do you like being told what to do, or being the one giving orders? 👑",
  "how does it feel to hand over control to me completely? 🔓",
  "what's an order you secretly wish I'd give you? 🤫",
  "would you wear something all day just because I told you to? 👗",
  "what's the most obedient thing you'd do to please me? 🙇",
  "be honest — do you want me softer or stricter with you? 🖤",
  "what 'rule' from me would actually turn you on to follow? 📜",
  "what would you call me if I were fully in charge tonight? 🗝️",
  "what's a reward you'd want for being good for me? 🍬",
  "what's the longest you'd let me make you wait? ⏳",
  // — keeping the spark alive over distance —
  "what do you miss most about me physically when we're apart? 🥺",
  "what's the hottest photo or video you've saved of me? 📲",
  "what do you do alone when you're aching to have me there? 🔥",
  "what's the first thing you'll do to me when we finally meet? ✈️",
  "what's a 'when we're together again' plan that's all yours? 🗓️",
  "what turns you on most about our late-night calls? 🌙",
  // — confessions & secret turn-ons —
  "when did you last think about me… in detail? ⏰",
  "what's the riskiest place you've imagined doing something with me? 🙊",
  "what's a secret turn-on you've never admitted to anyone? 🔐",
  "what's the dirtiest dream you've had about me? 💤",
  "what's something you act shy about but secretly love? 😇😈",
  "what's a word or phrase that instantly wrecks your focus? 🥵",
  "what's the most number of times I've crossed your mind in one day? 🔁",
  "have you ever had to 'behave' in public while thinking of me? 😳",
  // — preferences & dynamics —
  "lights on or off — and tell me why 💡",
  "teased to the edge slowly, or given it all at once? 🌋",
  "what name would you want me to call you in the moment? 🏷️",
  "do you get off more on praise, or on being told what to do? 🥇",
  "honestly — more romantic or more filthy with me? 🌹🔥",
  "would you rather be in control or completely at my mercy? ⚖️",
  "what's a 'beg for it' moment you'd actually enjoy? 🙏",
  "rough or gentle — and does it depend on the day? 🐺🕊️",
  // — fantasy depth & limits —
  "describe your ideal 'I'm completely yours tonight' scenario 🗝️",
  "what's a fantasy you'd only ever trust me with? 💍",
  "what's the boldest thing you'd let me film or photograph? 🎥",
  "what's one hard limit, and one thing you're dying to try? 🚧",
  "if I gave you a safe word right now, what would it be? 🛟",
  "what would 'losing all control with me' actually look like for you? 🌪️",
  // — explicit, over call & video —
  "how do you make yourself finish when you're thinking of me? 💦",
  "what would you want me to watch you do on cam right now? 🎥",
  "describe the last time you got off to the thought of me 🔥",
  "what's the filthiest thing you'd say to me on a late-night call? 🎙️",
  "how loud do you get when no one else is home? 🔊",
  "what do you want me to do to you the second the camera turns on? 📹",
  "fast and hard, or slow and deep — how do you want it tonight? 🌊",
  "where do you most want my mouth on you? 👅",
  "what's a sound I make that finishes you off? 🫦",
  "tell me exactly how you'd ride me if I were there 🐎",
  "what turns you on more — watching me, or being watched? 👀",
  "what would make you beg for it on call? 🙏",
  "how many times could you go in one night with me? 🔁",
  "what's the dirtiest thing you've done while we were on the phone? 📞",
  "talk me through your favourite way to be finished off 💥",
];

export const DARES_18: string[] = [
  // — send / show me something —
  "send me a teasing photo — your call how much you show 📸🔥",
  "send me a flirty selfie that's just for me, push your limit 😏",
  "voice-note me the filthiest sweet-nothing you can think of 🎙️",
  "describe what you're wearing right now (or what you'd take off) 👙",
  "video-call me and show me that outfit you know I love 📹",
  "send a photo of the spot you most want me to kiss 💋",
  // — say / describe —
  "describe exactly what you'd do to me if I were there right now 🛏️",
  "tell me, in detail, the fantasy you most want to try with me 🌶️",
  "tell me three things you want me to do to you tonight 😈",
  "describe how you'd kiss me from head to toe 💋",
  "set the scene for our perfect night in bed, start to finish 🕯️",
  "whisper the dirtiest thought you've had about me today 🤫",
  "tell me where you'd want my hands and mouth right now 🫦",
  "act out (or describe) how you'd undress me slowly 🌹",
  "talk me through your favourite memory of us in graphic detail 🔥",
  "narrate, step by step, how you'd tease me until I beg 😩",
  // — power-play: you pick something of theirs (consensual) —
  "let me choose your profile picture for the next 24 hours 🖼️",
  "let me write your bio/status — I get to pick the words ✍️",
  "I get to pick what you wear (or don't) for the rest of tonight 👗",
  "you're mine to command for the next 3 dares — say 'yes, captain' 🫡",
  "let me choose a pet name you have to answer to all night 🏷️",
  "hand me your phone and let me text 'us' anything I want for 5 min 📱",
  "I pick a 'rule' you must follow until the game ends — no breaking it 📜",
  "do the next dare exactly how I tell you to, no negotiating 👑",
  "let me set a dare you have to do later tonight, my choice ⏰",
  "you don't get to choose — I'll pick truth or dare for you next round 🎲",
  // — do something now —
  "send me a 10-second clip of your best slow striptease move 🎬",
  "bite your lip, undo one button, and send the photo 😈",
  "leave a mark somewhere only I'd find and send proof 💋",
  "touch yourself where you'd want me to and tell me how it feels 🔥",
  "do whatever I type next, right now, no questions ⚡",
  "get into the most tempting pose you can and snap it 📸🔥",
  "whisper my name the way you do when you're close, on voice note 🎙️",
  "edge yourself for 60 seconds and report back 🥵",
  // — day-long obedience & control (consensual; safeword always wins) —
  "be a slave to my words for the whole day — every request, no 'no' 👑",
  "you're mine to command for the next hour — text 'yes, yours' to start 🫡",
  "be my good [pet name] today — every task I send, you do and reply 'done' 🐾",
  "I'll text you little orders through the day — obey each one 📋",
  "say 'yes [my name]' to everything I ask for the next 10 minutes 🗣️",
  "no touching yourself today unless I say so — check in with me tonight ⛓️",
  "you don't get to finish until I allow it — tell me when you're close 🚦",
  "ask my permission before anything spicy tonight, and wait for my yes 🙏",
  "I set one rule you obey till midnight — break it and you owe me 📜",
  "hands behind your back — you move only when I say 🪢",
  // — partner's-choice outfits & reveals —
  "put on something I choose and send a photo to prove it 👗",
  "show me what you're wearing underneath — your tease, your pace 🙈",
  "wear something of mine (or my pick) all day and send proof 🧣",
  "let me choose your outfit for tomorrow, down to the underwear 👙",
  "wear only what I pick for our next video call 📹",
  "strip one layer each time I say 'next' on call 🎬",
  "model three looks for me and I'll pick what you keep on 🛍️",
  "send a mirror pic — I decide if you're allowed to change 🪞",
  // — LDR spice: tasks across the miles —
  "every hour today, send me one flirty photo on my command ⏰",
  "set a 'good morning' tease for me to wake up to tomorrow 🌅",
  "record a 15-second clip of exactly what you wish I was doing to you 🎥",
  "leave yourself one of my instructions for right before bed 🌙",
  "do whatever I type next on video, right now, no questions ⚡",
  "edge on my count over call and don't finish till I say 🥵",
  // — roleplay & sexting scenarios —
  "sext me like we just stumbled in from a date and can't wait 🚪",
  "roleplay: text me as a stranger flirting with me at a bar 🍸",
  "narrate a 'we almost got caught' scene, start to finish 🤫",
  "text me like it's the morning after our best night 🌅",
  "play two-truths-and-a-filthy-lie about what you want 🎭",
  "be my 'assistant' for 10 min and follow every instruction 📋",
  "pick a fantasy and act it out with me over voice note 🎙️",
  // — wagers, coupons & IOUs (consensual) —
  "write me an 'anything you want' coupon, redeemable anytime 🎟️",
  "loser of the next round loses one item of clothing — agree now 🎴",
  "owe me one 'no saying no' hour, my choice when ⏳",
  "bet a dare: if I win, you do my next 3 commands 🃏",
  "first one to blush owes the other a 'yes to anything' pass 🎟️",
  "give me a rain-check for one bold thing, due next time we meet 🧾",
  // — sensory & teasing —
  "ice cube challenge — use one and tell me exactly where 🧊",
  "blindfold on, phone on call, and let me talk you through it 🙈",
  "trace where you want to be kissed and send the picture ✍️",
  "describe a taste or touch you're craving from me right now 👅",
  "lose the top layer, then send a photo from your boldest angle 📐🔥",
  "leave a mark on yourself where only I'd get to see it 💋",
  // — extreme-but-consensual control —
  "you don't finish without my permission for the next 24h — agree? 🔒",
  "every text I send today, reply with what you'd do to me 💬",
  "be on call and follow my countdown — nothing till zero ⏱️",
  "kneel and ask me nicely for exactly what you want tonight 🧎🗣️",
  "let me decide your reward or denial when this game ends 🎰",
  "surrender your phone for 5 min — I get to set tonight's plan 📱👑",
  "pick a safe word, then put yourself fully in my hands 🗝️",
  // — explicit, over call & video (consensual; safe word always wins) —
  "get on video and touch yourself the way you do when you think of me 🎥",
  "show me on cam exactly where and how you want to be touched 👆🔥",
  "strip all the way down on video, slow, while I watch 🎬",
  "mutual on call — we both go until one of us finishes first 🏁",
  "touch yourself on my count and don't stop until I say ⏱️",
  "moan my name on the call like you actually mean it 🎙️",
  "show me your favourite toy and use it on video for me 🍆",
  "lie back, spread out on cam, and let me direct every move 📹",
  "talk me through what you'd do to me while you touch yourself 💬",
  "finish for me on camera — no faking it 💦",
  "edge yourself three times on call before I let you finish 🚦",
  "show me how turned on you are right now 🔥",
  "describe, in filthy detail, how you want me inside/around you 👅",
  "keep the camera where I tell you and don't move it 📐",
  "use your hands exactly how I narrate, live on cam ✋",
  "put on a show — tease me on video until I can't take it 🎭",
  "stay on the line and don't finish until we go together 🤝💥",
  "send a video of you saying the dirtiest thing you want tonight 🎥🤫",
];

export interface Dilemma { a: string; b: string }

export const WOULD_YOU_RATHER: Dilemma[] = [
  // — date nights & time together —
  { a: "a cosy night in 🛋️", b: "a night out together ✨" },
  { a: "breakfast in bed 🥐", b: "a sunrise walk 🌅" },
  { a: "a slow dance in the kitchen 💃", b: "a long drive with our songs 🚗" },
  { a: "movie marathon under blankets 🎬", b: "dancing till the lights come on 🪩" },
  { a: "candlelit dinner at home 🕯️", b: "street food adventure 🌮" },
  { a: "a picnic in the park 🧺", b: "a rooftop with a view 🌆" },
  { a: "lazy morning in bed ☕", b: "spontaneous day trip 🗺️" },
  { a: "game night, just us 🎲", b: "karaoke night, just us 🎤" },
  { a: "stay in our pyjamas all day 🐻", b: "dress up for no reason 👗" },
  { a: "cook a feast together 🍝", b: "order in and not move 🥡" },
  // — travel & dreams —
  { a: "travel the world 🌍", b: "build the perfect home 🏡" },
  { a: "beach holiday 🏝️", b: "mountain cabin 🏔️" },
  { a: "explore a new country every year ✈️", b: "have one place that's 'ours' 📍" },
  { a: "road trip with no plan 🚙", b: "a perfectly planned getaway 🗓️" },
  { a: "see the northern lights 🌌", b: "swim in a glowing sea 🌊" },
  { a: "a tiny cottage by the sea 🐚", b: "a loft in a big city 🏙️" },
  { a: "camp under the stars ⛺", b: "fancy hotel with room service 🛎️" },
  { a: "live by the ocean 🌅", b: "live in the mountains 🏔️" },
  // — sweet & sappy —
  { a: "always know what I'm thinking 💭", b: "always feel what I feel 💗" },
  { a: "relive our first date 🌸", b: "fast-forward to a future one 🔮" },
  { a: "handwritten letters 💌", b: "midnight phone calls ☎️" },
  { a: "matching tattoos 🖋️", b: "a song that's 'ours' 🎵" },
  { a: "forehead kisses 🥹", b: "hand squeezes 🤝" },
  { a: "good-morning texts every day ☀️", b: "good-night calls every night 🌙" },
  { a: "a love letter once a month ✉️", b: "a tiny surprise once a week 🎁" },
  { a: "fall asleep on a call 📞", b: "wake up to a voice note 🎙️" },
  { a: "a photo album of us 📷", b: "a playlist of our songs 🎶" },
  { a: "one long hug 🤗", b: "a hundred little kisses 😚" },
  { a: "never run out of things to say 🗨️", b: "be comfy in total silence 🤍" },
  // — playful 'this or that' —
  { a: "be the planner 📋", b: "be the surprise-r 🎉" },
  { a: "be each other's hype team 📣", b: "be each other's calm 🌊" },
  { a: "surprise gifts 🎁", b: "surprise plans 🎈" },
  { a: "win every argument 🏆", b: "always get the last cuddle 🫂" },
  { a: "share one giant dessert 🍰", b: "get your own, no sharing 🙅" },
  { a: "be little spoon forever 🥄", b: "be big spoon forever 🫧" },
  { a: "pick the movie every time 🍿", b: "pick the food every time 🍕" },
  { a: "control the playlist 🎧", b: "control the thermostat 🌡️" },
  { a: "stargaze till 3am ✨", b: "sleep in till noon 😴" },
  { a: "morning person together ☀️", b: "night owls together 🦉" },
  // — silly hypotheticals —
  { a: "swap voices for a day 🗣️", b: "swap dreams for a night 💤" },
  { a: "read each other's minds 🧠", b: "teleport to each other instantly ⚡" },
  { a: "only communicate in songs 🎵", b: "only communicate in emojis 😂" },
  { a: "have a pause button for life ⏸️", b: "have a rewind button 🔙" },
  { a: "be famous together 🌟", b: "be gloriously anonymous 🕶️" },
  { a: "a pet dragon 🐉", b: "a pet that does chores 🧹" },
  { a: "never need sleep 🌙", b: "never need money 💸" },
  { a: "always know the perfect thing to say 💬", b: "always give the perfect hug 🤗" },
  // — little life choices —
  { a: "a pet we raise together 🐶", b: "a garden we grow together 🌷" },
  { a: "cook together every night 🍳", b: "try every restaurant in town 🍽️" },
  { a: "a big noisy family dinner 🍗", b: "a quiet table for two 🥂" },
  { a: "weekend in the city 🌃", b: "weekend in nature 🌲" },
  { a: "a cat that loves us 🐱", b: "a dog that adores us 🐕" },
  { a: "host every gathering 🏠", b: "always be the guests 🎈" },
  { a: "early-to-bed cozy life 🛌", b: "late-night spontaneous life 🌜" },
  { a: "save up for one big trip 💰", b: "lots of little adventures 🎒" },
];
